# Generated by Django 3.0 on 2020-12-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('payment', models.URLField()),
                ('videos', models.URLField()),
                ('images_url', models.URLField()),
                ('image_main', models.ImageField(upload_to='')),
                ('image_one', models.ImageField(upload_to='')),
                ('image_two', models.ImageField(upload_to='')),
                ('image_three', models.ImageField(upload_to='')),
                ('image_four', models.ImageField(upload_to='')),
                ('image_five', models.ImageField(upload_to='')),
                ('image_seven', models.ImageField(upload_to='')),
                ('image_eight', models.ImageField(upload_to='')),
                ('image_nine', models.ImageField(upload_to='')),
            ],
        ),
    ]
