# Generated by Django 3.1.5 on 2021-04-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('payment', models.URLField()),
                ('videos', models.URLField()),
                ('images_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
