# Generated by Django 3.1.5 on 2021-04-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glavnaya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=225)),
                ('otpravka', models.CharField(max_length=225)),
                ('payment', models.CharField(max_length=225)),
                ('koment', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
